react/src/common.css
react/src/components/search.js
react/src/style.css

Make sure that the dropdown is always the same size as the search box

dropdown search with proper size

---

react/src/components/header.js
react/src/components/search.js

fixes rendering bug on f*refox

improve header consistency

---

react/src/components/article-panel.js
react/src/components/load-article.js

put the filtering into it. takes more out of the article class

add more to the load_article function

---

react/src/index.js

reported by twitter user averyhatestwt

no logo link on main page

---

react/src/components/comparison-panel.js
react/src/page_template/template.js

fix weird ordering bug

---

create_website.py

Resolves @lukebrody 's comment

fixed last reference to /home/kavi

---

notebooks/weather.ipynb
urbanstats/weather/era5.py
urbanstats/weather/global_bounding_boxes.py

haven't actually updated anything; this is just to let the download start running

global weather download

---

urbanstats/special_cases/ghsl_urban_center.py

Compare https://urbanstats.org/article.html?longname=Linyi+%28Northern+Shandong+Sheng%29+Urban+Center%2C+China and https://urbanstats.org/article.html?longname=Linyi+%28Southern+Shandong+Sheng%29+Urban+Center%2C+China
If lat2 > lat1, then 2 is more north than 1

"Northern" and "Southern"

---

produce_html_page.py
react/src/navigation/links.ts
urbanstats/ordinals/compute_ordinals.py
urbanstats/ordinals/output_ordering.py
urbanstats/protobuf/utils.py

shard files

---

produce_html_page.py
react/src/navigation/links.ts
react/src/quiz/sample.js
urbanstats/games/quiz.py

Do 3 hexes instead of 4 to significantly reduce the number of folders

improved sharding

---

README.md
create_website.py
react/package.json
react/watch.sh
react/webpack.config.js

Use `npm run watch ~/densitydb.github.io` to watch for JavaScript changes.
The site now auto-reloads.
Demo video:
https://github.com/user-attachments/assets/65f9c84a-af3b-4b8b-9871-1e3df76d0780

Update watch command, readme

---

react/src/utils/protos.d.ts
react/src/utils/protos.js

Just changing the protobuf objects. I'm pretty sure the only reason it was working before now was backwards compatibility

update protos to latest for the histogram

---

react/package-lock.json
react/package.json
react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/load-article.ts
react/src/components/plots.tsx
react/src/components/screenshot.tsx
react/src/components/sidebar.tsx
react/src/components/table.tsx
react/src/page_template/settings.ts
react/test/comparison_test.js
react/test/statistics_test.js

Split off from #300 for testing purposes. This should have 0 pixel-level effects on anything.

Add histograms invisibly

---

react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/map.tsx
react/src/components/mapper-panel.tsx
react/src/quiz/quiz-question.tsx
react/src/quiz/quiz-result.tsx

quiz fixes

---

react/src/page_template/template.tsx

Computer
Phone 
iPad
Computer 
Phone
iPad

Fix layout on ipad

---

create_website.py
produce_html_page.py
urbanstats/consolidated_data/produce_consolidated_data.py
urbanstats/export/export_csvs.py
urbanstats/games/quiz.py
urbanstats/games/quiz_custom.py
urbanstats/ordinals/compress_counts.py
urbanstats/ordinals/flat_ordinals.py
urbanstats/ordinals/ordering_info_outputter.py
urbanstats/ordinals/ordinal_info.py
urbanstats/statistics/extra_statistics.py
urbanstats/statistics/output_statistics_metadata.py

move code around outputting of statistics metadata to a file

---

react/src/about.tsx
react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/header.tsx
react/src/components/mapper-panel.tsx
react/src/components/plots-general.tsx
react/src/components/plots-histogram.tsx
react/src/components/plots.tsx
react/src/components/quiz-panel.tsx
react/src/components/screenshot.tsx
react/src/components/statistic-panel.tsx
react/src/components/table.tsx
react/src/data-credit.tsx
react/src/index.tsx
react/src/page_template/template.tsx

Use context for screenshot mode (#351, 1/2)

---

react/src/components/StatsTree.tsx
react/src/components/sidebar.css

Use expand triangle color from theme

---

react/eslint.config.mjs
react/package-lock.json
react/package.json
react/src/data-credit.tsx
react/src/style.css

Resolves https://github.com/kavigupta/urbanstats/issues/203

improve data credit

---

.github/workflows/check.yml
react/src/components/sidebar.tsx
react/test/scripts/run-e2e-tests.ts

Closes #432 
- Make a change and ensure it is caught
- Check artifacts

Combine screenshots check job with test job

---

react/src/page_template/template.tsx

Fix resize issue when hamburger open

---

react/src/article.tsx
react/src/comparison.tsx
react/src/discord-fix.tsx
react/src/quiz.tsx
react/src/statistic.tsx

Fix discord links

---

react/src/page_template/colors.ts

dark blue instead of dark green

dark mode color improvement

---

.github/workflows/check.yml
react/test/Dockerfile

Decrease container size by 25%
Shaves about 10 seconds off container pull time
[docker optimization.pdf](https://github.com/user-attachments/files/17601681/docker.optimization.pdf)
Removes video recording from tests

Improve docker performance

---

scripts/population_circle_exclusion.py
urbanstats/geometry/shapefiles/shapefile.py
urbanstats/geometry/shapefiles/shapefiles/population_circle.py

Setup for https://github.com/kavigupta/urbanstats/pull/511

add ability to exclude population circles

---

react/src/navigation/links.ts
react/src/statistic.tsx

Resolves https://github.com/kavigupta/urbanstats/issues/506

fix the discord links issue by just getting rid of % in links

---

react/src/components/statistic-panel.tsx

Similar improvement to #324
Fixes #467

Fix stat page number entry on mobile (fixes: #467)

---

react/src/components/StatsTree.tsx

Don’t show emojis on iOS

---

react/package-lock.json
react/package.json
react/rspack.config.js
react/tsconfig.json

Re-enable type checking

---

urbanstats/website_data/build.py

Broken in #545 
Should only fail in prod mode

Unbreak watch command when running on broken code

---

react/package-lock.json
react/package.json

This release fixes problems running locally on Mac

Install new testcafe

---

react/test/article-universe_test.ts
react/test/article_test.ts
react/test/search_test.ts
react/test/symlink_test.ts
react/test/test_utils.ts

This should reduce overhead when making settings vector changes

Eliminate checking settings in url in many places in tests where they’re not relevant

---

react/test/article_test.ts
react/test/comparison_test.ts
react/test/settings_test.ts
react/test/test_utils.ts

More cleaning up settings params from irrelevant tests

---

urbanstats/games/quiz.py
urbanstats/games/quiz_columns.py
urbanstats/games/quiz_region_types.py
urbanstats/statistics/statistic_collection.py

This does not change the quiz files at all

do not use index lists for quiz

---

urbanstats/statistics/collections/cdc_statistics.py
urbanstats/statistics/collections/census.py
urbanstats/statistics/collections/feature.py
urbanstats/statistics/collections/gpw.py
urbanstats/statistics/collections/segregation.py
urbanstats/statistics/collections/traffic_accidents.py
urbanstats/statistics/collections/us_election.py
urbanstats/statistics/collections/usda_fra_statistics.py
urbanstats/statistics/collections/weather.py
urbanstats/statistics/statistic_collection.py
urbanstats/website_data/table.py

move shapefile filtering to the statistics collection

---

.github/actions/python_environment/action.yml
.github/workflows/check.yml
react/test/Dockerfile

The performance improvement here isn't crazy (but still noticeable), and it splits things up nicely.

Keep the python environment in the github cache rather than in the docker image

---

react/src/load_json.ts
react/src/navigation/random.ts
react/src/quiz.tsx

Use async requests

---

urbanstats/special_cases/merge_international.py
urbanstats/website_data/table.py

Remove separate computation of US and international shapefiles ; delete merge

---

urbanstats/data/circle.py
urbanstats/geometry/shapefiles/shapefile.py
urbanstats/geometry/shapefiles/shapefile_subset.py
urbanstats/geometry/shapefiles/shapefiles/countries.py
urbanstats/geometry/shapefiles/shapefiles/subnational_regions.py
urbanstats/geometry/shapefiles/shapefiles/urban_centers.py
urbanstats/statistics/statistic_collection.py
urbanstats/weather/era5.py

Refactor. Does not change data

Abstract subset

---

react/src/components/table.tsx

sets it up so you can have other scenarios than just the +/- button. should not change anything

more general statistic name elements framework

---

react/src/components/search.tsx
react/test/search_test.ts

Closes #690 
Generally refactor search to be better
add regression test

Fix search crash

---

react/src/components/table.css
react/src/components/table.tsx
react/test/article-universe_test.ts
react/test/article_test.ts
react/test/comparison_test.ts

Does not change visuals at all

generalize editablenumber to work with arbitrary strings and styles

---

react/src/navigation/navigator.tsx
react/test/navigation_test.ts

Fix opening new tab

---

urbanstats-persistent-data/urbanstats_persistent_data/juxtastat_stats.py
urbanstats-persistent-data/urbanstats_persistent_data/main.py

This should be merged and deployed before #730 is. It doesn't do anything without the frontend

add friend tables and query system

---

react/test/quiz_test.ts

just get rid of the link test. it breaks every time we add more settings. the image test covers it fine

more stable quiz test

---

react/eslint.config.mjs
react/src/components/related-button.tsx
react/src/navigation/links.ts
react/src/navigation/navigator.tsx
react/test/article_test.ts
react/test/quiz_test_utils.ts

Closes #759 
This was always broken

Fix articles with many /

---

react/test/Dockerfile
react/test/quiz_test_utils.ts
urbanstats-persistent-data/run_for_test.sh
urbanstats-persistent-data/setup_for_test.sh

Save 1m on quiz_test and 30s on quiz_friends_test
Plus much neater log output
Plus killing the web sever works on Mac

Optimize quiz tests

---

react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/header.tsx
react/src/components/search.tsx
react/src/navigation/navigator.tsx
react/test/navigation_test.ts
react/test/search_test.ts
react/test/test_utils.ts

Add ability to control click search result

---

urbanstats/website_data/build.py

new game every day -> new quiz every day

---

react/src/quiz/dates.ts
react/src/quiz/quiz-components.tsx
react/src/quiz/quiz-friends.tsx
react/src/quiz/quiz-question.tsx
react/src/quiz/quiz-result.tsx
react/src/quiz/quiz-statistics.tsx
react/src/quiz/quiz.ts
react/src/quiz/statistics.ts

Use `QuizKind` or `QuizKindWithStats` rather than spamming `'juxtastat' | 'retrostat'` everywhere

better quiz kind typing system

---

react/src/common.css
react/src/quiz/quiz-friends.tsx
react/src/quiz/quiz.ts

https://github.com/user-attachments/assets/f7764f51-5910-4b34-a3ba-320aa06d5a1e
In light mode
https://github.com/user-attachments/assets/98fa568c-c1c5-48a2-bcdc-71f014cea7df

Add loading spinner and disable buttons while adding friend

---

.github/workflows/check.yml
react/test/scripts/ci_proxy.ts

Seeing errors here: https://github.com/kavigupta/urbanstats/actions/runs/12496493572/job/34868296575

Attempt to fix CI 429s by including GITHUB_TOKEN with requests

---

react/src/quiz/quiz-friends.tsx

https://github.com/user-attachments/assets/865627d3-41ea-4d53-82aa-71b112c15e99

Add loading indicator while loading scores

---

react/src/quiz/quiz-friends.tsx

https://github.com/user-attachments/assets/02ded9eb-f8e7-4cbc-a857-b780628f960c

Add loading indicator while removing friend

---

react/src/components/quiz-panel.tsx
react/src/quiz/quiz-components.tsx
react/src/quiz/quiz-friends.tsx
react/src/quiz/quiz-result.tsx
react/src/quiz/quiz.ts
react/src/quiz/statistics.ts

This allows us to change quiz model data without reloading the page.

Refactor - Wrap quiz localStorage in a data logic class

---

.github/workflows/check.yml
requirements.txt
tests/check_images.py
tests/utils_test.py

also, run linter on `tests/`; and fix lint issues with tha folder

Run python tests

---

.github/actions/python_environment/action.yml
README.md
requirements.txt
requirements_torch.txt

Needs to be in a separate file because of https://github.com/pypa/pip/issues/12233

add torch to requirements

---

react/eslint.config.mjs
react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/quiz-panel.tsx
react/src/components/statistic-panel.tsx
react/src/navigation/PageDescriptor.ts
react/src/navigation/routers.tsx

Improve document title

---

react/src/components/IndexPanel.tsx
react/src/components/article-panel.tsx
react/src/components/comparison-panel.tsx
react/src/components/header.tsx
react/src/components/map.tsx
react/src/components/related-button.tsx
react/src/components/sidebar.tsx
react/src/components/statistic-panel.tsx
react/src/components/table.tsx
react/src/navigation/Navigator.ts
react/src/navigation/routers.tsx
react/src/quiz/quiz-result.tsx
react/test/article_test.ts

Closes #838 
Before
https://github.com/user-attachments/assets/3d8497ed-8c92-4a65-9adc-53c844dc1b65
After
https://github.com/user-attachments/assets/bab262bc-546c-4ff3-9b24-454e89a9662e

Maintain scroll position when article title length changes

---

react/src/components/map.tsx
react/test/article_test.ts

Before
https://github.com/user-attachments/assets/dfe0f35d-2889-40af-937c-d0886e8c2268
After
https://github.com/user-attachments/assets/33649083-7481-453b-a6db-9430654e011a

Scroll relative to map when navigating within map

---

react/src/components/map.tsx
react/test/article_test.ts

Fix map navigation bug

---

react/src/components/search.tsx
react/test/article-universe_test.ts
react/test/article_test.ts
react/test/comparison_test.ts
react/test/navigation_test.ts
react/test/settings_test.ts
react/test/test_utils.ts

Allow search to work asynchronously
Also refactor into utils

Refactor and fix tests involving search

---

react/src/page_template/template.tsx
react/src/quiz/quiz-result.tsx
react/test/quiz_infinite_test.ts

compact representation of emoji should not be applied to short emoji sequences

---

react/test/settings_test.ts

Fix https://github.com/kavigupta/urbanstats/actions/runs/13213820349/job/36890707264

Fix settings test failure

---

urbanstats/statistics/statistics_tree.py

make exported category identifiers the same as the ones in the sidebar

---

react/eslint.config.mjs
react/src/navigation/PageDescriptor.ts
react/src/navigation/random.ts
react/src/page_template/template.tsx
react/test/random_test.ts
react/unit/random.test.ts
react/unit/util/localStorage.ts

No pc in random

---

react/src/navigation/PageDescriptor.ts
react/src/navigation/random.ts
react/unit/random.test.ts

Adds: by population test (domestic and full)
Fix unit testing to not assume URL encoding

fix unit random tests

---

react/src/load_json.ts
react/src/utils/symlinks.ts
urbanstats/website_data/create_article_gzips.py
urbanstats/website_data/sharding.py

always include symlink files

---

react/src/components/header.tsx
react/test/search_test.ts

Fix search sidebar mobile

---

react/package-lock.json
react/package.json
react/src/search.ts

Search cache

---

react/src/components/statistic-panel.tsx
react/test/statistics_test.ts

Fix stat off by one

---

react/src/components/map.tsx
react/src/page_template/template.tsx

Resolves #1038 
just make sure to refresh the map a few times on load. there's probably a more principled fix but this works fine
Tested on {firefox, chrome} * {my laptop, my phone (android)} * {my desktop server}; the error reproduces pre fix and does not post fix

fix the 2 map loading issue

---

react/src/components/map.tsx

fine, i'll document the fix for area smh

documentation for why we trigger "unnecessary" updates the first 5x

---

react/src/components/map.tsx

Might help with https://github.com/kavigupta/urbanstats/issues/1038

separate out populateMap and also fix some map loading stuff

---

react/src/navigation/Navigator.ts

Closes #728 
Manual testing for the fix, test suite for regressions

Fix page load race

---

.github/workflows/check.yml
react/test/scripts/run-e2e-tests.ts

The flag has no effect besides making tests not work on Mac

Remove --disable-gpu flag during e2e tests

---

urbanstats/data/gpw.py
urbanstats/data/population_overlays.py
urbanstats/statistics/collections/gpw.py

This has been validated to ensure no data changes

Allow variable resolution

---

react/src/components/map.tsx
react/test/article.test.ts

Fix map main region clickabilitiy

---

urbanstats-persistent-data/run.sh

Empirically this works on the deployed server

only one worker

---

react/src/components/map.tsx

Effectively Resolves #102  since the basemap has labels on it

move polygons below labels

---

.github/workflows/check.yml
react/package-lock.json
react/package.json
react/test/quiz_auth_test_utils.ts
react/test/quiz_test_utils.ts

Fix quiz auth tests

---

react/test/test_utils.ts

Log network errors

---

react/test/mapper.test.ts
react/test/quiz_test_template.ts
react/test/test_utils.ts

Motivated by https://github.com/kavigupta/urbanstats/actions/runs/17185239000/job/48753371338?pr=1133

Require extensions for downloads

---

react/src/components/map.tsx
react/src/syau/syau-map.tsx

updateFn should take a version argument

---

react/test/scripts/run-e2e-tests.ts

We were responding incorrectly toe the baseRef option

Fix retries on master
