kavigupta/urbanstats

- react/src/components/article-panel.js
offset created by checkboxes being checked no longer causes ordinals not to update. Fixes #111
> Bugfix: checkbox offset ordinals

- .github/workflows/check.yml
- react/.gitignore
- react/test/Dockerfile
- tests/check_images.py
- Refactor e2e test names from "./test_file.ts" to "test_file" this simplifies operations throughout the pipeline.
- Add the following to the `testcafe` runner:
- Fixed window size
- Disable scorllbars
- Disable GPU acceleration
- Disable thumbnails
- Enable videos (available as artifacts from test runs)
- Add `check_screenshots` job that runs `check_images.py` for each e2e test
- Add `merge_screenshots` job that merges screenshots and deltas from all e2e tests into one convenient artifact
- Modify `check_images.py`
- Include a mode where you can pass the specific test to check with `--test=`
- Add explicit checks that expected reference and actual files exist, error when one is missing
- Copy screenshots that have changed from reference to a `changed_screenshots` folder
> (3/3) Image checking CI

- react/src/components/related-button.tsx
- react/src/components/sidebar.tsx
Previously, you could only click the box itself.
Allowing clicking the labels improves ergonomics by increasing the clickable area.
Also, clicking checkbox labels is a standard UX expectation.
https://github.com/user-attachments/assets/7d808f78-bbf3-4412-b802-60b95b825f1e
> Add support for clicking check labels

- react/src/about.tsx
- react/src/components/article-panel.tsx
- react/src/components/comparison-panel.tsx
- react/src/components/header.tsx
- react/src/components/mapper-panel.tsx
- react/src/components/quiz-panel.tsx
- react/src/components/related-button.tsx
- react/src/components/sidebar.tsx
- react/src/components/statistic-panel.tsx
- react/src/data-credit.tsx
- react/src/page_template/template.tsx
- react/src/quiz/quiz-components.tsx
- react/src/quiz/quiz-question.tsx
- react/src/quiz/quiz-result.tsx
- react/src/utils/responsive.ts
https://github.com/user-attachments/assets/48465505-111c-47f6-8ac9-4c0d0d2acbc7
We should support laying out the page again when the window size changes.
- Change the `mobileLayout` function to a `useMobileLayout` hook. Have it sync with the window size.
- Refactor other layout functions to also be hooks.
- Refactor the usage of these functions to conform to React hook rules.
- **Refactor quiz requests to conform to React rules, so that multiple requests don't get sent on page resize**
> (2/3) Use responsive hooks

- .github/workflows/check.yml
Forgot to escape regexes in jq gsub
> Fix the e2e test runner on files with “ts” in the name

- .github/workflows/check.yml
This artifact accomplished nothing besides taking up space in most cases, since there are the same as the reference screenshots except for changed_screenshots, which is its own artifact.
The one exception is testing the comparison code in CI, but developer could add this back in that case.
> Remove screenshots artifact

- react/eslint.config.mjs
- react/test/article_test.ts
- react/test/link_settings_test_template.ts
- react/test/quiz_test.ts
- react/test/settings_test.ts
- react/test/stats_tree_test_template.ts
- react/test/test_utils.ts
We still see occasional test failures due to "navigation interrupted eval"
This should fix this by ensuring the navigation happens after the eval
Add eslint rule to ensure that we don't accidentally use location.reload
> Implement safe reload

- .github/actions/node_modules/action.yml
- .github/workflows/check.yml
- urbanstats/website_data/build.py
Use Github cache instead of reinstalling the modules
Saves about 10s each time they need to install
Which totals to about 30s every run
> cache node_modules

- .github/actions/docker_image/action.yml
- .github/workflows/check.yml
- Dockerfile
- react/test/Dockerfile
We had just one Dockerfile for all jobs, which was overkill, as some jobs (e.g. linting) don't need packages (e.g. Chromium) that only are used for e2e testing.
The Dockerfile without chromium is smaller and faster.
> Split dockerfiles in two

- .github/workflows/check.yml
Needed because of this: https://github.com/orgs/community/discussions/119459
This does mean pushes to a branch are not going to trigger workflows unless you open a PR
> trigger actions on pull_request not just push

- urbanstats/geometry/shapefiles/shapefiles/continents.py
- urbanstats/geometry/shapefiles/shapefiles/countries.py
- urbanstats/geometry/shapefiles/shapefiles/subnational_regions.py
because a lot of the intermediate versions are in caches with the shapefile boundaries
> bump versions of shapefiles

- react/src/components/map.tsx
- react/src/navigation/navigator.tsx
Do this by parallelizing shapefile requests
Also, parallelize requests when loading stats page
Before (artificial 100ms latency)
https://github.com/user-attachments/assets/2f004b93-c2ec-4c02-9281-31dbdcd611d3
After (artificial 100ms latency)
https://github.com/user-attachments/assets/536186b8-f17a-414f-82ae-69e442dbfcae
> Improve map loading performance on high-latency connections

- react/src/components/QuerySettingsConnection.tsx
- react/src/navigation/navigator.tsx
- react/src/navigation/routers.tsx
- react/test/navigation_test.ts
- Get out of staging mode if we go to a non-settings-vector page.
- Changes to scroll position handling
- Save scroll position as part of the history state
- Restore scroll position on back/forward
- Scroll to top when navigating to different kinds of pages
- Add somewhat graceful handling of history state evolution, use zod schemas to parse it, and reload if failure.
- Add an effect system for navigator page loads, so that loading a page can have effects that are executed after it renders. (This is used for scrolling ,etc)
- Move around some event listeners into the navigator rather than in the router.
Closes #715 
Closes #716
> Improve SPA

- react/test/navigation_test.ts
Revert #763 which didn't really make since since Testcafe waited 5s anyways.
The problem was that we were trying to scroll the loading screen 🤦
> fix navigation scroll test

- react/test/test_utils.ts
Because we're an SPA, we need to wait for initial loading before doing things on the page
> Fix stats tree mobile test

- react/test/test_utils.ts
Follow up to #769 
we need a positive check rather than a negative check so we don’t succeed before the loading screen even shows up
> Fix stats_tree_mobile test, actually this time.

- react/src/components/table.tsx
Was running into a modified version of https://www.npmjs.com/package/react-contenteditable#known-issues
where react will batch re-rendering from useState as a performance optimization
the problem was that an old state that was batched would get rendered in while typing, overwriting a newer one
Debug version of react-contenteditable (place in node_modules/react-contenteditable/lib)
[react-contenteditable.js.zip](https://github.com/user-attachments/files/18176498/react-contenteditable.js.zip)
> Fix quiz friends test flakiness

- react/src/components/IndexPanel.tsx
- react/src/components/article-panel.tsx
- react/src/components/comparison-panel.tsx
- react/src/components/header.tsx
- react/src/components/map.tsx
- react/src/components/related-button.tsx
- react/src/components/sidebar.tsx
- react/src/components/statistic-panel.tsx
- react/src/components/table.tsx
- react/src/navigation/navigator.tsx
- react/src/quiz/quiz-result.tsx
- react/test/navigation_test.ts
- react/test/test_utils.ts
Makes reasoning about where the page will end up after the navigation very easy
Allows features like "Related" articles on articles page scrolling to top, while pointer arrows keep position
> Explicitly specify scroll on every navigation

- react/src/components/table.tsx
- react/test/article_test.ts
this is in prep for a later change that entirely removes the overall ordinal. It is kept for now but all it is used for is determining whether to show the pointers
I did just do this for both ordinals to avoid more complicated logic. On my laptop it consistently adds <1ms (two Date.now() calls do not record any timing difference at all), so it's fine imo to just do it even if its a bit redundant in some cases
Adds a bit of delay because otherwise the test was flaking. Not sure why this just came up (as described above there isn't really any reason this should be slowing things down?)
> use data index for overall ordinal

- react/test/quiz_friends_link_test.ts
- react/test/quiz_friends_test.ts
- react/test/quiz_test_utils.ts
Closes #785 
ClientFunctions have built-in retry, while t.eval does not
https://testcafe.io/documentation/402837/guides/basic-guides/assertions#use-assertions-to-extract-page-information
> Fix flaky quiz_friends tests

- react/rspack.config.js
Don't know why this was happening or why this fixes it, but binary search with git blame and file changes found the problem, so I don't care to find out since it's pretty inconsequential.
> Fix linting on local

- react/src/components/quiz-panel.tsx
- react/test/quiz_test_utils.ts
- react/test/test_utils.ts
doesn't do much now but is important for infinite quiz
> wait for quiz loading before pressing button

- react/watch.sh
The python build step for the site can take a while, but sometimes you just want to restart the rspack watcher
So, press ^C once and wait 1 second to just restart the watcher, press ^C again once the watcher shuts down to stop watching entirely.
> Implement better watch script

- react/test/memory_article_test.ts
- react/test/memory_home_test.ts
- react/test/memory_search_article_test.ts
- react/test/memory_search_test.ts
- react/test/memory_test_utils.ts
Memory tests were totally wrong, we were just double counting the page if there were any workers
> Fix memory tests

- react/src/components/map.tsx
- react/src/components/mapper-panel.tsx
do not attempt to load after every polygon is adedd
> optimize the loading of polygons in the mapper

- react/rspack.config.js
This allows connecting from a phone on a local network without looking up a changing IP address
> Add “.local” as allowed host on dev server
